package com.unpsjb.machineturing.model;
/**
 * Estados de la máquina
 */
public enum State {
    INIT, 
    COPY_READ,
    COPY_WRITE,
    SHIFT_LEFT_A_START, 
    SHIFT_LEFT_A_READ, 
    SHIFT_LEFT_A_WRITE, 
    SHIFT_LEFT_A_FILL_ZERO,
    XOR_A_COMPARE,
    SHIFT_RIGHT_B_START, 
    SHIFT_RIGHT_B_READ, 
    SHIFT_RIGHT_B_WRITE, 
    SHIFT_RIGHT_B_FILL_ZERO,
    XOR_B_COMPARE,
    SHIFT_LEFT_C_START, 
    SHIFT_LEFT_C_READ, 
    SHIFT_LEFT_C_WRITE, 
    SHIFT_LEFT_C_FILL_ZERO,
    XOR_C_COMPARE,
    COMPARE_VALUES,
    NEW_ITERATION, 
    CYCLE_DETECTED,
    HALT
}
